# Generated by Django 5.0.2 on 2024-02-14 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabCompanies',
            fields=[
                ('CompanyID', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('LocationID', models.AutoField(primary_key=True, serialize=False)),
                ('LocationName', models.CharField(max_length=255)),
                ('Latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('Longitude', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('RouteID', models.AutoField(primary_key=True, serialize=False)),
                ('VehicleType', models.CharField(max_length=50)),
                ('RouteName', models.CharField(max_length=255)),
                ('FarePerKM', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CabFareStructure',
            fields=[
                ('CompanyID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.cabcompanies')),
                ('BasePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PricePerKM', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Distance', models.DecimalField(decimal_places=1, max_digits=3)),
                ('DestinationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='core.locations')),
                ('SourceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='core.locations')),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('ScheduleID', models.AutoField(primary_key=True, serialize=False)),
                ('DepartureTime', models.TimeField()),
                ('RouteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.routes')),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('StopID', models.IntegerField(primary_key=True, serialize=False)),
                ('StopName', models.CharField(max_length=250)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.locations')),
            ],
        ),
        migrations.CreateModel(
            name='RouteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StopSequence', models.IntegerField()),
                ('ArrivalTime', models.TimeField()),
                ('RouteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.routes')),
                ('StopID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stops')),
            ],
            options={
                'unique_together': {('RouteID', 'StopSequence')},
            },
        ),
    ]
