# Generated by Django 5.0.2 on 2024-02-14 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='DestinationID',
            field=models.ForeignKey(db_column='DestinationID', on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='core.locations'),
        ),
        migrations.AlterField(
            model_name='connections',
            name='SourceID',
            field=models.ForeignKey(db_column='SourceID', on_delete=django.db.models.deletion.CASCADE, related_name='source', to='core.locations'),
        ),
        migrations.AlterField(
            model_name='routedetails',
            name='RouteID',
            field=models.ForeignKey(db_column='RouteID', on_delete=django.db.models.deletion.CASCADE, to='core.routes'),
        ),
        migrations.AlterField(
            model_name='routedetails',
            name='StopID',
            field=models.ForeignKey(db_column='StopID', on_delete=django.db.models.deletion.CASCADE, to='core.stops'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='RouteID',
            field=models.ForeignKey(db_column='RouteID', on_delete=django.db.models.deletion.CASCADE, to='core.routes'),
        ),
        migrations.AlterField(
            model_name='stops',
            name='Location',
            field=models.ForeignKey(db_column='Location', on_delete=django.db.models.deletion.CASCADE, to='core.locations'),
        ),
    ]
