# Generated by Django 5.0.2 on 2024-02-29 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_location_stops_locationid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name_plural': 'Locations'},
        ),
    ]
