# Generated by Django 5.0.2 on 2024-03-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cabfarestructure_basekm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabcompanies',
            options={'verbose_name_plural': 'Cab Companies'},
        ),
        migrations.AlterModelOptions(
            name='cabfarestructure',
            options={'verbose_name_plural': 'Cab Fare Structures'},
        ),
        migrations.AlterModelOptions(
            name='connections',
            options={'verbose_name_plural': 'Connections'},
        ),
        migrations.AlterModelOptions(
            name='routedetails',
            options={'verbose_name_plural': 'Route Details'},
        ),
        migrations.AlterModelOptions(
            name='routes',
            options={'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterModelOptions(
            name='stops',
            options={'verbose_name_plural': 'Stops'},
        ),
    ]
